@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@baseUrl = http://{{host}}
@contentType = application/json



# GET {{baseUrl}}/language HTTP/1.1
# Accept-Language: he

POST {{baseUrl}}/language/he HTTP/1.1
