@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@baseUrl = http://{{host}}/api
@contentType = application/json


### main
GET {{baseUrl}} HTTP/1.1

### example
GET {{baseUrl}}/example/1234?filter=true HTTP/1.1
content-type: application/json

{
    "content":"bla bla bla"
}


### login
POST {{baseUrl}}/auth/login
Content-Type: application/x-www-form-urlencoded

email=a@a.com&password=Aq123456